const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const daySchema = new Schema(
  {
    date: {
      type: String,
    },
    stocks: {
      type: Object,
      default: {
        XU100: null,
        AEFES: null,
        AGHOL: null,
        AHGAZ: null,
        AKBNK: null,
        AKCNS: null,
        AKFGY: null,
        AKSA: null,
        AKSEN: null,
        ALARK: null,
        ALBRK: null,
        ALFAS: null,
        ARCLK: null,
        ASELS: null,
        ASTOR: null,
        ASUZU: null,
        AYDEM: null,
        BAGFS: null,
        BERA: null,
        BIMAS: null,
        BIOEN: null,
        BRSAN: null,
        BRYAT: null,
        BUCIM: null,
        CANTE: null,
        CCOLA: null,
        CEMTS: null,
        CIMSA: null,
        DOAS: null,
        DOHOL: null,
        ECILC: null,
        ECZYT: null,
        EGEEN: null,
        EKGYO: null,
        ENJSA: null,
        ENKAI: null,
        EREGL: null,
        EUREN: null,
        FROTO: null,
        GARAN: null,
        GENIL: null,
        GESAN: null,
        GLYHO: null,
        GSDHO: null,
        GUBRF: null,
        GWIND: null,
        HALKB: null,
        HEKTS: null,
        IPEKE: null,
        ISCTR: null,
        ISDMR: null,
        ISGYO: null,
        ISMEN: null,
        IZMDC: null,
        KARSN: null,
        KCAER: null,
        KCHOL: null,
        KMPUR: null,
        KONTR: null,
        KONYA: null,
        KORDS: null,
        KOZAA: null,
        KOZAL: null,
        KRDMD: null,
        KZBGY: null,
        MAVI: null,
        MGROS: null,
        ODAS: null,
        OTKAR: null,
        OYAKC: null,
        PENTA: null,
        PETKM: null,
        PGSUS: null,
        PSGYO: null,
        QUAGR: null,
        SAHOL: null,
        SASA: null,
        SELEC: null,
        SISE: null,
        SKBNK: null,
        SMRTG: null,
        SNGYO: null,
        SOKM: null,
        TAVHL: null,
        TCELL: null,
        THYAO: null,
        TKFEN: null,
        TKNSA: null,
        TOASO: null,
        TSKB: null,
        TTKOM: null,
        TTRAK: null,
        TUKAS: null,
        TUPRS: null,
        ULKER: null,
        VAKBN: null,
        VESBE: null,
        VESTL: null,
        YKBNK: null,
        YYLGD: null,
        ZOREN: null,
      },
    },
    usd_to_try: {
      type: Number,
    },
  },
  { timestamps: { createdAt: "created_at", updatedAt: "updated_at" } }
);

module.exports = mongoose.model("Day", daySchema);
